name: Update neovim-nightly Cask (from template)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scripts/update_neovim_nightly.sh
          scripts/update_neovim_nightly.sh

      - name: Create Pull Request (if changed)
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(cask): update neovim-nightly from template"
          title: "Update neovim-nightly Cask checksums"
          body: |
            Automated update of `Casks/neovim-nightly.rb` using `tmpl/neovim-nightly.rb` as template.
            Nightly assets checked on: ${{ github.run_id }}
          branch: chore/update-neovim-nightly
          delete-branch: true
          add-paths: |
            Casks/neovim-nightly.rb